[build]
base = "frontend"
publish = "frontend/dist"
command = "npm run build"

[build.environment]
VITE_REACT_APP_API_URL = "https://gpec-backend.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
